# 📂 Limpeza e preparação de dados em Python

**Professora:** Dra. Isadora Garcia Ferrão

📧 [instagram](https://www.instagram.com/isadora.ferrao/)

🌐 [linkedin](https://www.linkedin.com/in/isadora-ferrao/)

---

## Introdução à limpeza de dados

## Qualidade de dados

Antes de analisar dados, precisamos garantir que eles possuem **boa qualidade**.

Dados de baixa qualidade podem gerar:

- análises incorretas
- modelos imprecisos
- decisões erradas

Por isso, uma etapa importante da análise de dados é a **limpeza de dados (data cleaning)**.

## Problemas comuns em datasets

Alguns problemas comuns são:

- valores ausentes
- dados duplicados
- valores inconsistentes
- formatos incorretos

In [40]:
import pandas as pd

url = "https://raw.githubusercontent.com/datasciencedojo/datasets/master/titanic.csv"

df = pd.read_csv(url)

df.head()

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S

In [41]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 891 entries, 0 to 890
Data columns (total 12 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   PassengerId  891 non-null    int64
 1   Survived     891 non-null    int64
 2   Pclass       891 non-null    int64
 3   Name         891 non-null    object
 4   Sex          891 non-null    object
 5   Age          714 non-null    float64
 6   SibSp        891 non-null    int64
 7   Parch        891 non-null    int64
 8   Ticket       891 non-null    object
 9   Fare         891 non-null    float64
 10  Cabin        204 non-null    object
 11  Embarked     889 non-null    object
dtypes: float64(2), int64(5), object(5)
memory usage: 83.7+ KB

In [42]:
df.describe()

,PassengerId,Survived,Pclass,Age,SibSp,Parch,Fare
count,891.000000,891.000000,891.000000,714.000000,891.000000,891.000000,891.000000
mean,446.000000,0.383838,2.308642,29.699118,0.523008,0.381594,32.204208
std,257.353842,0.486592,0.836071,14.526497,1.102743,0.806057,49.693429
min,1.000000,0.000000,1.000000,0.420000,0.000000,0.000000,0.000000
25%,223.500000,0.000000,2.000000,20.125000,0.000000,0.000000,7.910400
50%,446.000000,0.000000,3.000000,28.000000,0.000000,0.000000,14.454200
75%,668.500000,1.000000,3.000000,38.000000,1.000000,0.000000,31.000000
max,891.000000,1.000000,3.000000,80.000000,8.000000,6.000000,512.329200

# Tratamento de valores ausentes

## O que é NaN?

NaN significa **Not a Number**.

Ele representa **valores ausentes ou desconhecidos** em um dataset.

In [43]:
df.isnull().sum()

PassengerId      0
Survived         0
Pclass           0
Name             0
Sex              0
Age            177
SibSp            0
Parch            0
Ticket           0
Fare             0
Cabin          687
Embarked         2
dtype: int64

## Remoção de valores ausentes

In [44]:
df_limpo = df.dropna()

df_limpo.head()

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
6,7,0,1,"McCarthy, Mr. Timothy J",male,54.0,0,0,17463,51.8625,E46,S
10,11,1,3,"Sandstrom, Miss. Marguerite Rut",female,4.0,1,1,PP 9549,16.7000,G6,S
11,12,1,1,"Bonnell, Miss. Elizabeth",female,58.0,0,0,113783,26.5500,C103,S

In [45]:
df_limpo.isnull().sum()

PassengerId    0
Survived       0
Pclass         0
Name           0
Sex            0
Age            0
SibSp          0
Parch          0
Ticket         0
Fare           0
Cabin          0
Embarked       0
dtype: int64

## Preenchimento de valores ausentes

Em vez de remover dados, podemos preencher os valores faltantes.

In [46]:
df["Age"] = df["Age"].fillna(df["Age"].mean())

In [47]:
df["Age"].isnull().sum()

0

In [48]:
df.isnull().sum()

PassengerId      0
Survived         0
Pclass           0
Name             0
Sex              0
Age              0
SibSp            0
Parch            0
Ticket           0
Fare             0
Cabin          687
Embarked         2
dtype: int64

# Normalização e padronização

## Transformação de variáveis

Às vezes precisamos transformar dados para facilitar a análise.

In [49]:
# Aqui apenas duplica a coluna:

df["Age_duplicada"] = df["Age"].apply(lambda x: x)

In [50]:
print(df["Age_duplicada"])

0      22.000000
1      38.000000
2      26.000000
3      35.000000
4      35.000000
         ...
886    27.000000
887    19.000000
888    29.699118
889    26.000000
890    32.000000
Name: Age_duplicada, Length: 891, dtype: float64

In [51]:
# Aqui apenas duplica a coluna:
import numpy as np

df["Age_log"] = df["Age"].apply(lambda x: np.log(x))

In [52]:
print(df["Age_log"])

0      3.091042
1      3.637586
2      3.258097
3      3.555348
4      3.555348
         ...
886    3.295837
887    2.944439
888    3.391117
889    3.258097
890    3.465736
Name: Age_log, Length: 891, dtype: float64

## Escala de dados

Em alguns casos precisamos colocar os dados na mesma escala.

##### TÉCNICA MIN-MAX ----- COLOCA OS VALORES DENTRO DO INTERVALO DE 0 ATÉ 1 !!!

In [53]:
df["Fare_normalized"] = (df["Fare"] - df["Fare"].min()) / (df["Fare"].max() - df["Fare"].min())

df.head()

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked,Age_duplicada,Age_log,Fare_normalized
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S,22.0,3.091042,0.014151
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C,38.0,3.637586,0.139136
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S,26.0,3.258097,0.015469
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S,35.0,3.555348,0.103644
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S,35.0,3.555348,0.015713

In [54]:
df.describe()

,PassengerId,Survived,Pclass,Age,SibSp,Parch,Fare,Age_duplicada,Age_log,Fare_normalized
count,891.000000,891.000000,891.000000,891.000000,891.000000,891.000000,891.000000,891.000000,891.000000,891.000000
mean,446.000000,0.383838,2.308642,29.699118,0.523008,0.381594,32.204208,29.699118,3.234606,0.062858
std,257.353842,0.486592,0.836071,13.002015,1.102743,0.806057,49.693429,13.002015,0.706606,0.096995
min,1.000000,0.000000,1.000000,0.420000,0.000000,0.000000,0.000000,0.420000,-0.867501,0.000000
25%,223.500000,0.000000,2.000000,22.000000,0.000000,0.000000,7.910400,22.000000,3.091042,0.015440
50%,446.000000,0.000000,3.000000,29.699118,0.000000,0.000000,14.454200,29.699118,3.391117,0.028213
75%,668.500000,1.000000,3.000000,35.000000,1.000000,0.000000,31.000000,35.000000,3.555348,0.060508
max,891.000000,1.000000,3.000000,80.000000,8.000000,6.000000,512.329200,80.000000,4.382027,1.000000

# Automação de Pré-processamento

## Pipelines de dados

Um pipeline de dados executa várias etapas automaticamente:

1. carregar dados  
2. limpar dados  
3. transformar dados  
4. gerar dataset final

In [57]:
def limpar_dados(df):

    df["Age"] = df["Age"].fillna(df["Age"].mean())
    #df["Age"].fillna(df["Age"].mean(), inplace=True)

    df["Fare_normalized"] = (
        df["Fare"] - df["Fare"].min()
    ) / (df["Fare"].max() - df["Fare"].min())

    return df

In [59]:
df = limpar_dados(df)

df.head()

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked,Age_duplicada,Age_log,Fare_normalized
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S,22.0,3.091042,0.014151
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C,38.0,3.637586,0.139136
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S,26.0,3.258097,0.015469
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S,35.0,3.555348,0.103644
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S,35.0,3.555348,0.015713

In [60]:
df.describe()

,PassengerId,Survived,Pclass,Age,SibSp,Parch,Fare,Age_duplicada,Age_log,Fare_normalized
count,891.000000,891.000000,891.000000,891.000000,891.000000,891.000000,891.000000,891.000000,891.000000,891.000000
mean,446.000000,0.383838,2.308642,29.699118,0.523008,0.381594,32.204208,29.699118,3.234606,0.062858
std,257.353842,0.486592,0.836071,13.002015,1.102743,0.806057,49.693429,13.002015,0.706606,0.096995
min,1.000000,0.000000,1.000000,0.420000,0.000000,0.000000,0.000000,0.420000,-0.867501,0.000000
25%,223.500000,0.000000,2.000000,22.000000,0.000000,0.000000,7.910400,22.000000,3.091042,0.015440
50%,446.000000,0.000000,3.000000,29.699118,0.000000,0.000000,14.454200,29.699118,3.391117,0.028213
75%,668.500000,1.000000,3.000000,35.000000,1.000000,0.000000,31.000000,35.000000,3.555348,0.060508
max,891.000000,1.000000,3.000000,80.000000,8.000000,6.000000,512.329200,80.000000,4.382027,1.000000

# Documentação e validação

## Reprodutibilidade

Uma análise deve ser **reproduzível**.

Isso significa que qualquer pessoa deve conseguir:

- executar o código
- obter os mesmos resultados

## Validação de datasets

Antes de usar um dataset, devemos verificar:

- valores ausentes
- tipos de dados
- consistência

In [61]:
def validar_dataset(df):

    print("Linhas:", df.shape[0])
    print("Colunas:", df.shape[1])
    print("\nValores ausentes:")

    print(df.isnull().sum())

In [62]:
validar_dataset(df)

Linhas: 891
Colunas: 15

Valores ausentes:
PassengerId          0
Survived             0
Pclass               0
Name                 0
Sex                  0
Age                  0
SibSp                0
Parch                0
Ticket               0
Fare                 0
Cabin              687
Embarked             2
Age_duplicada        0
Age_log              0
Fare_normalized      0
dtype: int64